- name: web  
  image: php:8.2-apache
  env: 
    - name: DB_HOST 
      value: db
    - name: DB_DATABASE
      value: accommo_venientdb 
    - name: DB_USER
      value: root
    - name: DB_PASSWORD  
      value: null

  ports:
    - containerPort: 80
      name: http  
  volumes:
    - name: code-volume
      hostPath:
        path: .